shinyUI(
        tagList(
                conditionalPanel(
                        condition=(isDesktop),
                        uiDesktop()),
                conditionalPanel(
                        condition=(isMobile),
                        uiMobile())
        )
)
