uiSourceItemConfig <- function(){
        tabPanel(icon('wrench'),
                 value = 'config',
                 br(),
                 fluidRow(
                         column(3,
                                selectInput('extSourceList',
                                            'Datenquellen:',
                                            srcTabUiList,
                                            multiple=TRUE, 
                                            selectize=FALSE),
                                htmlOutput('extSourceItemDeleteError', 
                                           style='color:red'),
                                actionButton('delExtSourceList', 'Entfernen', 
                                             icon('trash')),
                                actionButton('loadExtSourceList', 'Download', 
                                             icon('download'))),
                         column(8,
                                textInput('extSourceItemName',
                                          'Name:'),
                                tags$label('Ansicht (ui.R):'),
                                br(),
                                tags$textarea(id='extSourceItemUi',
                                              rows=5, cols=80),
                                br(),
                                tags$label('Logik (server.R):'),
                                br(),
                                tags$textarea(id='extSourceItemLogic',
                                              rows=5, cols=80),
                                br(),
                                htmlOutput('extSourceItemError', 
                                           style='color:red'),
                                actionButton('addExtSourceItem', 
                                             'Hinzufügen', icon('plus')),
                                actionButton('updateExtSourceItem', 
                                             'Aktualisieren', icon('edit'))
                         )
                 ),
                 bsModal('loadExtSourceListDialog',
                         'Erweiterungen laden',
                         'loadExtSourceList',
                         size = 'small',
                         selectInput('extSourceView',
                                     'Quelle:',
                                     c('SAM'='sam', 'Github'='github'),
                                     selectize=FALSE),
                         conditionalPanel(
                                 condition = 'input.extSourceView == \"sam\"',
                                 selectInput('extSourceListSam',
                                             'Auswahl:',                                                                       
                                             c('Visual #1', 'Visual #2'),
                                             multiple=TRUE, selectize=FALSE),
                                 actionButton('addExtSourceItemSam', 'Hinzufügen', icon('plus'))),
                         conditionalPanel(
                                 condition = 'input.extSourceView == \"github\"',
                                 textInput('extSourceItemGithub',
                                           'Pfad:', 
                                           value = 'https://github.com/OwnYourData/extensions/tree/master/sample'),
                                 htmlOutput('extSourceItemGithubError', style='color:red'),
                                 htmlOutput('extSourceItemGithubSuccess', style='color:green'),
                                 actionButton('addExtSourceItemGithub', 'Hinzufügen', icon('plus')),
                                 helpText('Im angegebenen Verzeichnis werden die Dateien oyd.json, ext_ui.R und ext_server.R ausgelesen.'))
                 ),
                 uiOutput('loadExtSourceListDialogCloseScript')
        )
}