uiStatusItemConfig <- function(){
        tabPanel(icon('wrench'),
                 value = 'config',
                 br(),
                 fluidRow(
                         column(3,
                                selectInput('extStatusList',
                                            'Auswertungen:',
                                            statTabUiList,
                                            multiple=TRUE, 
                                            selectize=FALSE),
                                htmlOutput('extStatusItemDeleteError', 
                                           style='color:red'),
                                actionButton('delExtStatusList', 'Entfernen', 
                                             icon('trash')),
                                actionButton('loadExtStatusList', 'Download', 
                                             icon('download'))),
                         column(8,
                                textInput('extStatusItemName',
                                          'Name:'),
                                tags$label('Ansicht (ui.R):'),
                                br(),
                                tags$textarea(id='extStatusItemUi',
                                              rows=5, cols=80),
                                br(),
                                tags$label('Logik (server.R):'),
                                br(),
                                tags$textarea(id='extStatusItemLogic',
                                              rows=5, cols=80),
                                br(),
                                htmlOutput('extStatusItemError', 
                                           style='color:red'),
                                actionButton('addExtStatusItem', 
                                             'Hinzufügen', icon('plus')),
                                actionButton('updateExtStatusItem', 
                                             'Aktualisieren', icon('edit'))
                         )
                 ),
                 bsModal('loadExtStatusListDialog',
                         'Erweiterungen laden',
                         'loadExtStatusList',
                         size = 'small',
                         selectInput('extStatusView',
                                     'Quelle:',
                                     c('SAM'='sam', 'Github'='github'),
                                     selectize=FALSE),
                         conditionalPanel(
                                 condition = 'input.extStatusView == \"sam\"',
                                 selectInput('extStatusListSam',
                                             'Auswahl:',                                                                       
                                             c('Visual #1', 'Visual #2'),
                                             multiple=TRUE, selectize=FALSE),
                                 actionButton('addExtStatusItemSam', 'Hinzufügen', icon('plus'))),
                         conditionalPanel(
                                 condition = 'input.extStatusView == \"github\"',
                                 textInput('extStatusItemGithub',
                                           'Pfad:', 
                                           value = 'https://github.com/OwnYourData/extensions/tree/master/sample'),
                                 htmlOutput('extStatusItemGithubError', style='color:red'),
                                 htmlOutput('extStatusItemGithubSuccess', style='color:green'),
                                 actionButton('addExtStatusItemGithub', 'Hinzufügen', icon('plus')),
                                 helpText('Im angegebenen Verzeichnis werden die Dateien oyd.json, ext_ui.R und ext_server.R ausgelesen.'))
                 ),
                 uiOutput('loadExtStatusListDialogCloseScript')
        )
}