uiStart <- function(){
        bsModal('startConfig', 'Assistent zur Konfiguration', 'launchDialog', size='large',
                bsCollapse(id = "collapse", open = "Willkommen",
                           bsCollapsePanel("Willkommen (Schritt 1 von 3)",
                                           value="Willkommen",
                                           "Dieser Assistent hilft dir dabei die App einzurichten. Klicke auf 'Weiter', um zum nächsten Schritt zu gelangen!",
                                           br(),br(),
                                           actionButton("p1next", "Weiter"),
                                           style = "primary"),
                           bsCollapsePanel("PIA (Schritt 2 von 3)",
                                           value="PIA",
                                           "Trage hier die Verbindungdaten zu deiner PIA und den darin gespeicherten Daten ein. Du findest diese Informationen in der PIA im Menü 'Entitäten' unter 'Plugin'; gehe dort zur aktuellen App und klicke zum Anzeigen der Informationen auf 'Bearbeiten'.",
                                           br(),br(),
                                           textInput('modalPiaUrl', 'URL:'),
                                           textInput('modalPiaId', 'ID:'),
                                           textInput('modalPiaSecret', 'Secret:'),
                                           br(),
                                           actionButton('p2prev', 'Zurück'),
                                           actionButton('p2next', 'Speichern & Weiter'),
                                           style = "info"),
                           bsCollapsePanel("Fertig (Schritt 3 von 3)",
                                           value="Fertig",
                                           "Gratulation! Du hast alle notwendigen Einstellungen vorgenommen und kannst nun die App verwenden. Solltest du später eine Änderung vornehmen wollen, findest du alle Konfigurationsmöglichkeiten im Bereich 'Einstellungen'.",
                                           br(),br(),
                                           actionButton('p3prev', 'Zurück'),
                                           actionButton('p3close', 'Fertig'),
                                           style = "info")
                )
        )
}